name: Manual-build  # When pushing to any branch then run this action
# Env variable
env:
  DOCKER_USER: ${{ vars.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  REPO_NAME: ${{ vars.REPO_NAME }}

on: workflow_dispatch

jobs: # job name 
  build-deploy: 
    runs-on: ubuntu-latest  # runner name : (ubuntu latest version)     
    steps:
      - uses: actions/checkout@v3 # first action : checkout source code
      - name: take gnucashversion
        run: |
          echo "GNUCASH_VERSION=$(curl -s https://archlinux.org/packages/community/x86_64/gnucash/  | grep  softwareVersion | sed -E 's/.*content=\"(.*)\".*/\1/g')" >> $GITHUB_ENV
      - name: docker login
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASSWORD }}
      - name: Build the Docker image # push The image to the docker hub
        uses: docker/build-push-action@v3
        with:
          context: .
          tags: ${{ env.REPO_NAME }}:${{ env.GNUCASH_VERSION }},${{ env.REPO_NAME }}:latest
          push: true
